# Generated by Django 3.1 on 2021-06-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_auto_20210604_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnotes',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='electronics.subject'),
        ),
        migrations.AddField(
            model_name='video_lectures',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='electronics.subject'),
        ),
    ]
