# Generated by Django 3.1 on 2021-06-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_auto_20210604_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_form',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
