# Generated by Django 3.1 on 2021-06-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0004_subject_short_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='short_form',
            new_name='shortname',
        ),
    ]
