# Generated by Django 3.1 on 2021-06-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0005_auto_20210604_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='shortname',
        ),
    ]
