# Generated by Django 3.1 on 2021-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0006_remove_subject_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_full_form',
            field=models.CharField(default='XYZ', max_length=100),
        ),
    ]
