# Generated by Django 3.1 on 2021-06-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0007_subject_subject_full_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_lectures',
            name='video_thumb',
            field=models.FileField(blank=True, upload_to='Video_thumbnails'),
        ),
    ]
