# Generated by Django 3.1 on 2021-06-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0008_video_lectures_video_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnotes',
            name='classnotes_thumbnail',
            field=models.FileField(blank=True, upload_to='Classnotes_thumbnail'),
        ),
    ]
