# Generated by Django 3.1 on 2021-06-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0009_classnotes_classnotes_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory_videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_number', models.IntegerField()),
                ('content_file', models.FileField(upload_to='Laboratory Videos')),
                ('laboratory_video_thumb', models.FileField(blank=True, upload_to='Laboratory_video_thumbnails')),
                ('experiment_title', models.CharField(max_length=100)),
                ('topic_name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='electronics.subject')),
            ],
        ),
    ]
