# Generated by Django 3.1 on 2021-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0010_laboratory_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classnotes',
            name='title',
        ),
        migrations.AlterField(
            model_name='unit_info',
            name='image',
            field=models.ImageField(upload_to='Unit_images/'),
        ),
    ]
