# Generated by Django 3.1 on 2021-06-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0011_auto_20210613_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory_videos',
            name='experiment_title',
        ),
        migrations.RemoveField(
            model_name='video_lectures',
            name='title',
        ),
    ]
