# Generated by Django 3.1 on 2021-06-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0012_auto_20210613_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnotes',
            name='image',
            field=models.CharField(choices=[('PDF', 'PDF'), ('Word Doc', 'Word Doc'), ('PPT', 'PPT')], default='PDF', max_length=256),
        ),
    ]
