# Generated by Django 3.1 on 2021-06-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0013_classnotes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classnotes',
            old_name='image',
            new_name='doc_type',
        ),
    ]
