# Generated by Django 3.1 on 2021-06-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0014_auto_20210613_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classnotes',
            name='classnotes_thumbnail',
        ),
    ]
