# Generated by Django 3.1 on 2021-06-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0015_remove_classnotes_classnotes_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnotes',
            name='unit_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.unit_info'),
        ),
    ]
