# Generated by Django 3.1 on 2021-06-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0020_classnotes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnotes',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classnotes',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
