# Generated by Django 3.1 on 2021-06-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0021_auto_20210614_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
