# Generated by Django 3.1 on 2021-06-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0024_auto_20210615_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.FileField(upload_to='Subject_Images'),
        ),
    ]
