# Generated by Django 3.1 on 2021-06-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0026_subject_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.IntegerField(),
        ),
    ]
