# Generated by Django 3.1 on 2021-06-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0029_auto_20210615_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_videos',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='laboratory_videos',
            name='unit_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=256),
        ),
        migrations.AddField(
            model_name='video_lectures',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video_lectures',
            name='unit_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=256),
        ),
    ]
