# Generated by Django 3.1 on 2021-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0030_auto_20210615_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory_videos',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laboratory_videos',
            name='unit_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=256),
        ),
        migrations.AlterField(
            model_name='video_lectures',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video_lectures',
            name='unit_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=256),
        ),
    ]
