# Generated by Django 3.1 on 2021-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0031_auto_20210615_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_lectures',
            name='lecture_number',
            field=models.IntegerField(default=1),
        ),
    ]
