# Generated by Django 3.1 on 2021-06-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0033_auto_20210616_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_info',
            name='unit_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=256),
        ),
    ]
