# Generated by Django 3.1 on 2021-06-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0036_auto_20210617_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123', max_length=32),
        ),
    ]
