# Generated by Django 3.1 on 2021-06-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0038_auto_20210617_0028'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
